# Generated by Django 5.1.5 on 2025-04-01 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KanBanData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="John Doe", max_length=100)),
                (
                    "email",
                    models.EmailField(default="john@example.com", max_length=254),
                ),
                ("phone", models.CharField(default="123-456-7890", max_length=20)),
                ("company", models.CharField(default="Acme Inc", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(default="Interested in our premium plan")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "KanBan Data",
                "verbose_name_plural": "KanBan Data",
                "ordering": ["-created_at"],
            },
        ),
    ]
