# Generated by Django 5.1.5 on 2025-04-02 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0002_alter_kanbandata_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kanbandata",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "KanBan Data",
                "verbose_name_plural": "KanBan Data",
            },
        ),
    ]
